_BASE_: "Base-SparseRCNN.yaml"
MODEL:
  WEIGHTS: "/home/dff/f/code/CenterNet2/models/R-50.pkl"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  SparseRCNN:
    NUM_PROPOSALS: 400
    NUM_CLASSES: 732
DATASETS:
  TRAIN: ("uni_train_mini",)
  TEST: ("uni_val_mini",)
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
  CHECKPOINT_PERIOD: 1000000000
INPUT:
  CROP:
    ENABLED: False
  FORMAT: "RGB"
